INSERT IGNORE INTO dish (name, type) VALUES ('Bruschetta', 'appetizer');
INSERT IGNORE INTO dish (name, type) VALUES ('Chicken Satay', 'appetizer');
INSERT IGNORE INTO dish (name, type) VALUES ('Caprese Skewers', 'appetizer');
INSERT IGNORE INTO dish (name, type) VALUES ('Spinach and Artichoke Dip', 'appetizer');
INSERT IGNORE INTO dish (name, type) VALUES ('Stuffed Mushrooms', 'appetizer');
INSERT IGNORE INTO dish (name, type) VALUES ('Shrimp Cocktail', 'appetizer');
INSERT IGNORE INTO dish (name, type) VALUES ('Deviled Eggs', 'appetizer');
INSERT IGNORE INTO dish (name, type) VALUES ('Mini Quiches', 'appetizer');
INSERT IGNORE INTO dish (name, type) VALUES ('Guacamole', 'appetizer');
INSERT IGNORE INTO dish (name, type) VALUES ('Chicken Wings', 'appetizer');
INSERT IGNORE INTO dish (name, type) VALUES ('Spaghetti Bolognese', 'main_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Grilled Salmon', 'main_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Beef Stir-Fry', 'main_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Chicken Parmesan', 'main_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Tacos', 'main_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Vegetable Curry', 'main_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('BBQ Ribs', 'main_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Margherita Pizza', 'main_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Beef Burritos', 'main_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Chicken Fajitas', 'main_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Garlic Mashed Potatoes', 'side_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Grilled Vegetables', 'side_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Coleslaw', 'side_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Rice Pilaf', 'side_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Baked Beans', 'side_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Cornbread', 'side_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Caesar Salad', 'side_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Roasted Brussels Sprouts', 'side_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Creamed Spinach', 'side_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Roasted Potatoes', 'side_dish');
INSERT IGNORE INTO dish (name, type) VALUES ('Chocolate Chip Cookies', 'dessert');
INSERT IGNORE INTO dish (name, type) VALUES ('Apple Pie', 'dessert');
INSERT IGNORE INTO dish (name, type) VALUES ('Cheesecake', 'dessert');
INSERT IGNORE INTO dish (name, type) VALUES ('Brownies', 'dessert');
INSERT IGNORE INTO dish (name, type) VALUES ('Tiramisu', 'dessert');
INSERT IGNORE INTO dish (name, type) VALUES ('Fruit Salad', 'dessert');
INSERT IGNORE INTO dish (name, type) VALUES ('Creme Brulee', 'dessert');
INSERT IGNORE INTO dish (name, type) VALUES ('Carrot Cake', 'dessert');
INSERT IGNORE INTO dish (name, type) VALUES ('Panna Cotta', 'dessert');
INSERT IGNORE INTO dish (name, type) VALUES ('Lemon Bars', 'dessert');
INSERT IGNORE INTO dish (name, type) VALUES ('Mojito', 'drink');
INSERT IGNORE INTO dish (name, type) VALUES ('Margarita', 'drink');
INSERT IGNORE INTO dish (name, type) VALUES ('Strawberry Smoothie', 'drink');
INSERT IGNORE INTO dish (name, type) VALUES ('Old Fashioned', 'drink');
INSERT IGNORE INTO dish (name, type) VALUES ('Piña Colada', 'drink');
INSERT IGNORE INTO dish (name, type) VALUES ('Mango Lassi', 'drink');
INSERT IGNORE INTO dish (name, type) VALUES ('Hot Chocolate', 'drink');
INSERT IGNORE INTO dish (name, type) VALUES ('Iced Tea', 'drink');
INSERT IGNORE INTO dish (name, type) VALUES ('Espresso Martini', 'drink');
INSERT IGNORE INTO dish (name, type) VALUES ('Sparkling Lemonade', 'drink');
INSERT IGNORE INTO ingredient (name, price) VALUES ('Baguette', 1.33);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Tomatoes', 3.18);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 2.68);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Fresh basil', 3.99);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Olive oil', 1.79);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Balsamic vinegar', 2.92);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 1.0);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 2.9);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Chicken breast', 3.89);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Soy sauce', 2.84);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Peanut butter', 2.82);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lime juice', 1.22);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 2.63);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ginger', 1.44);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Brown sugar', 1.19);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Skewers', 2.12);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cherry tomatoes', 2.0);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Fresh mozzarella balls', 1.13);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Basil leaves', 3.15);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Balsamic glaze', 1.74);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 1.97);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 3.15);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Spinach', 3.67);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Artichoke hearts', 2.51);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cream cheese', 2.7);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sour cream', 3.92);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Mayonnaise', 2.09);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Parmesan cheese', 1.99);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 2.01);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 1.03);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 3.4);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Button mushrooms', 2.54);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Breadcrumbs', 2.32);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Parmesan cheese', 3.11);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 3.37);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Parsley', 3.07);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Olive oil', 3.71);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 2.01);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 2.45);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Shrimp', 1.71);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cocktail sauce', 2.4);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lemon wedges', 3.68);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Fresh dill', 1.27);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Eggs', 3.09);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Mayonnaise', 3.79);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Dijon mustard', 1.83);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pickle relish', 1.92);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Paprika', 1.91);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 2.41);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 3.34);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pie crust', 3.38);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Eggs', 2.6);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Milk', 3.97);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cheese', 3.21);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Spinach', 1.37);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Mushrooms', 2.75);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Onions', 1.04);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 1.44);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 1.79);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Avocado', 2.29);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lime juice', 3.07);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Tomato', 1.22);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Onion', 2.15);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 2.9);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cilantro', 3.84);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 1.37);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 2.85);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Chicken wings', 1.59);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Hot sauce', 3.14);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Butter', 2.78);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic powder', 3.97);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 3.08);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 3.45);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ground beef', 3.82);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Spaghetti', 3.31);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Tomato sauce', 2.93);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Onion', 3.57);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 2.89);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Carrot', 3.32);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Celery', 3.72);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Red wine', 3.54);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Olive oil', 1.95);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 3.86);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 1.91);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salmon fillets', 2.64);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lemon', 3.91);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Olive oil', 1.38);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 2.86);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Dill', 3.37);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 2.14);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 3.31);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Beef strips', 3.47);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Soy sauce', 1.41);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ginger', 1.35);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 3.49);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Broccoli', 3.07);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Bell peppers', 1.75);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Carrots', 3.38);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Onions', 2.99);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Vegetable oil', 3.41);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Chicken breast', 1.47);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Breadcrumbs', 3.96);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Parmesan cheese', 3.76);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Marinara sauce', 2.44);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Mozzarella cheese', 1.75);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Spaghetti', 1.34);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Olive oil', 1.17);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 3.54);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 1.55);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Tortillas', 3.83);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ground beef', 1.7);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lettuce', 2.11);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Tomatoes', 3.64);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cheese', 2.67);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salsa', 2.2);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sour cream', 2.45);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Guacamole', 2.51);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Mixed vegetables', 1.93);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Curry paste', 1.54);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Coconut milk', 3.21);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Onion', 3.5);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 2.14);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ginger', 3.06);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Vegetable oil', 1.26);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 3.37);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 3.77);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pork ribs', 1.06);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Bbq sauce', 3.29);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Brown sugar', 3.64);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Paprika', 2.02);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic powder', 2.56);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Onion powder', 1.54);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 1.77);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 2.51);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pizza dough', 1.32);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Tomato sauce', 2.86);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Mozzarella cheese', 2.95);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Fresh basil', 2.65);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Olive oil', 2.76);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 1.36);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 3.67);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Flour tortillas', 3.93);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ground beef', 1.17);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Rice', 3.05);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Beans', 1.7);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cheese', 1.51);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salsa', 2.55);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sour cream', 2.35);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lettuce', 2.1);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Chicken breast', 3.14);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Bell peppers', 1.81);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Onions', 3.0);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Fajita seasoning', 2.97);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Tortillas', 1.04);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Guacamole', 2.42);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sour cream', 2.18);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salsa', 3.73);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Potatoes', 1.03);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 3.25);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Butter', 2.62);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Milk', 3.23);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 1.0);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 3.62);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Assorted vegetables', 3.74);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Olive oil', 2.68);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Balsamic vinegar', 2.9);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 3.75);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 1.42);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cabbage', 2.55);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Carrots', 1.61);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Mayonnaise', 3.51);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Vinegar', 2.71);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 3.33);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 3.45);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 3.37);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Rice', 3.0);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Onion', 3.98);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 1.49);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Chicken or vegetable broth', 2.39);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Butter', 2.39);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 3.67);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 2.11);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Canned baked beans', 2.3);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Bacon', 3.6);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Onion', 1.69);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Brown sugar', 3.64);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Molasses', 1.64);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Mustard', 3.27);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 1.01);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 2.53);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cornmeal', 2.72);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Flour', 2.36);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 3.13);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Baking powder', 2.93);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Milk', 1.69);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Eggs', 2.91);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Butter', 3.43);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 2.44);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Romaine lettuce', 1.95);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Croutons', 3.43);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Parmesan cheese', 1.31);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Caesar dressing', 1.07);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Brussels sprouts', 1.41);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Olive oil', 3.74);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 2.58);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 3.73);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 3.89);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Spinach', 1.93);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cream cheese', 3.66);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Heavy cream', 3.75);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 2.48);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Nutmeg', 1.72);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 1.44);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 2.66);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Potatoes', 3.82);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Olive oil', 3.8);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Garlic', 2.31);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Rosemary', 3.4);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 3.36);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pepper', 3.48);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Flour', 1.54);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Butter', 3.48);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 2.76);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Brown sugar', 3.39);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Eggs', 3.91);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Vanilla extract', 2.75);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Chocolate chips', 3.73);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Baking soda', 2.9);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 2.92);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pie crust', 2.81);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Apples', 2.15);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 1.78);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cinnamon', 2.49);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lemon juice', 1.98);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Butter', 2.66);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cream cheese', 3.87);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 2.41);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Eggs', 2.59);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sour cream', 3.87);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Vanilla extract', 3.9);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Graham cracker crust', 2.03);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Flour', 2.33);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cocoa powder', 2.83);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 2.97);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Butter', 2.73);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Eggs', 2.02);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Vanilla extract', 3.02);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Chocolate chips', 2.84);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 2.12);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ladyfingers', 1.5);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Mascarpone cheese', 2.95);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Coffee', 1.72);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cocoa powder', 2.67);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 3.36);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Rum', 1.42);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Eggs', 1.09);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Assorted fruits', 2.74);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Honey', 2.43);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lemon juice', 3.61);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Mint leaves', 2.49);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Heavy cream', 2.38);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 2.66);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Vanilla extract', 3.4);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Egg yolks', 3.76);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Flour', 1.94);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 2.67);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Carrots', 3.6);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Eggs', 1.82);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Vegetable oil', 1.92);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Baking powder', 1.22);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cinnamon', 1.27);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cream cheese frosting', 1.58);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Heavy cream', 1.52);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 3.66);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Gelatin', 1.5);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Vanilla extract', 3.66);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Fresh berries', 1.71);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Flour', 1.42);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Butter', 2.58);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 3.17);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Eggs', 2.68);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lemon juice', 3.95);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lemon zest', 2.3);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Powdered sugar', 1.25);
INSERT IGNORE INTO ingredient (name, price) VALUES ('White rum', 3.95);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lime juice', 3.81);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Mint leaves', 3.68);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 1.17);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Soda water', 2.53);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ice', 3.29);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Tequila', 2.74);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lime juice', 1.85);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Triple sec', 3.87);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Salt', 2.66);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ice', 3.35);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Strawberries', 3.92);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Yogurt', 1.9);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Milk', 3.46);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Honey', 2.93);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ice', 3.43);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Whiskey', 2.3);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 3.42);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Bitters', 2.66);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Orange peel', 3.75);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ice', 2.16);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Pineapple juice', 2.26);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Coconut cream', 3.77);
INSERT IGNORE INTO ingredient (name, price) VALUES ('White rum', 2.19);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ice', 2.6);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Mango', 3.9);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Yogurt', 3.99);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 2.55);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cardamom', 1.42);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ice', 1.39);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Milk', 2.57);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Cocoa powder', 2.69);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 1.32);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Vanilla extract', 2.85);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Whipped cream', 2.44);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Chocolate shavings', 1.18);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Tea bags', 1.5);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Water', 2.0);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 3.47);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lemon slices', 1.75);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ice', 1.43);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Vodka', 3.94);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Espresso', 1.94);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Coffee liqueur', 2.47);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar syrup', 2.55);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ice', 2.72);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lemon juice', 3.91);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sparkling water', 1.8);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Sugar', 2.19);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Lemon slices', 2.69);
INSERT IGNORE INTO ingredient (name, price) VALUES ('Ice', 2.47);
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Baguette' FROM dish d WHERE d.name = 'Bruschetta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Tomatoes' FROM dish d WHERE d.name = 'Bruschetta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Bruschetta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Fresh basil' FROM dish d WHERE d.name = 'Bruschetta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Olive oil' FROM dish d WHERE d.name = 'Bruschetta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Balsamic vinegar' FROM dish d WHERE d.name = 'Bruschetta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Bruschetta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Bruschetta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Chicken breast' FROM dish d WHERE d.name = 'Chicken Satay';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Soy sauce' FROM dish d WHERE d.name = 'Chicken Satay';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Peanut butter' FROM dish d WHERE d.name = 'Chicken Satay';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lime juice' FROM dish d WHERE d.name = 'Chicken Satay';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Chicken Satay';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ginger' FROM dish d WHERE d.name = 'Chicken Satay';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Brown sugar' FROM dish d WHERE d.name = 'Chicken Satay';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Skewers' FROM dish d WHERE d.name = 'Chicken Satay';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cherry tomatoes' FROM dish d WHERE d.name = 'Caprese Skewers';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Fresh mozzarella balls' FROM dish d WHERE d.name = 'Caprese Skewers';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Basil leaves' FROM dish d WHERE d.name = 'Caprese Skewers';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Balsamic glaze' FROM dish d WHERE d.name = 'Caprese Skewers';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Caprese Skewers';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Caprese Skewers';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Spinach' FROM dish d WHERE d.name = 'Spinach and Artichoke Dip';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Artichoke hearts' FROM dish d WHERE d.name = 'Spinach and Artichoke Dip';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cream cheese' FROM dish d WHERE d.name = 'Spinach and Artichoke Dip';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sour cream' FROM dish d WHERE d.name = 'Spinach and Artichoke Dip';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Mayonnaise' FROM dish d WHERE d.name = 'Spinach and Artichoke Dip';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Parmesan cheese' FROM dish d WHERE d.name = 'Spinach and Artichoke Dip';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Spinach and Artichoke Dip';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Spinach and Artichoke Dip';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Spinach and Artichoke Dip';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Button mushrooms' FROM dish d WHERE d.name = 'Stuffed Mushrooms';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Breadcrumbs' FROM dish d WHERE d.name = 'Stuffed Mushrooms';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Parmesan cheese' FROM dish d WHERE d.name = 'Stuffed Mushrooms';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Stuffed Mushrooms';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Parsley' FROM dish d WHERE d.name = 'Stuffed Mushrooms';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Olive oil' FROM dish d WHERE d.name = 'Stuffed Mushrooms';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Stuffed Mushrooms';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Stuffed Mushrooms';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Shrimp' FROM dish d WHERE d.name = 'Shrimp Cocktail';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cocktail sauce' FROM dish d WHERE d.name = 'Shrimp Cocktail';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lemon wedges' FROM dish d WHERE d.name = 'Shrimp Cocktail';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Fresh dill' FROM dish d WHERE d.name = 'Shrimp Cocktail';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Eggs' FROM dish d WHERE d.name = 'Deviled Eggs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Mayonnaise' FROM dish d WHERE d.name = 'Deviled Eggs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Dijon mustard' FROM dish d WHERE d.name = 'Deviled Eggs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pickle relish' FROM dish d WHERE d.name = 'Deviled Eggs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Paprika' FROM dish d WHERE d.name = 'Deviled Eggs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Deviled Eggs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Deviled Eggs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pie crust' FROM dish d WHERE d.name = 'Mini Quiches';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Eggs' FROM dish d WHERE d.name = 'Mini Quiches';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Milk' FROM dish d WHERE d.name = 'Mini Quiches';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cheese' FROM dish d WHERE d.name = 'Mini Quiches';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Spinach' FROM dish d WHERE d.name = 'Mini Quiches';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Mushrooms' FROM dish d WHERE d.name = 'Mini Quiches';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Onions' FROM dish d WHERE d.name = 'Mini Quiches';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Mini Quiches';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Mini Quiches';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Avocado' FROM dish d WHERE d.name = 'Guacamole';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lime juice' FROM dish d WHERE d.name = 'Guacamole';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Tomato' FROM dish d WHERE d.name = 'Guacamole';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Onion' FROM dish d WHERE d.name = 'Guacamole';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Guacamole';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cilantro' FROM dish d WHERE d.name = 'Guacamole';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Guacamole';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Guacamole';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Chicken wings' FROM dish d WHERE d.name = 'Chicken Wings';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Hot sauce' FROM dish d WHERE d.name = 'Chicken Wings';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Butter' FROM dish d WHERE d.name = 'Chicken Wings';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic powder' FROM dish d WHERE d.name = 'Chicken Wings';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Chicken Wings';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Chicken Wings';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ground beef' FROM dish d WHERE d.name = 'Spaghetti Bolognese';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Spaghetti' FROM dish d WHERE d.name = 'Spaghetti Bolognese';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Tomato sauce' FROM dish d WHERE d.name = 'Spaghetti Bolognese';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Onion' FROM dish d WHERE d.name = 'Spaghetti Bolognese';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Spaghetti Bolognese';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Carrot' FROM dish d WHERE d.name = 'Spaghetti Bolognese';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Celery' FROM dish d WHERE d.name = 'Spaghetti Bolognese';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Red wine' FROM dish d WHERE d.name = 'Spaghetti Bolognese';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Olive oil' FROM dish d WHERE d.name = 'Spaghetti Bolognese';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Spaghetti Bolognese';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Spaghetti Bolognese';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salmon fillets' FROM dish d WHERE d.name = 'Grilled Salmon';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lemon' FROM dish d WHERE d.name = 'Grilled Salmon';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Olive oil' FROM dish d WHERE d.name = 'Grilled Salmon';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Grilled Salmon';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Dill' FROM dish d WHERE d.name = 'Grilled Salmon';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Grilled Salmon';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Grilled Salmon';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Beef strips' FROM dish d WHERE d.name = 'Beef Stir-Fry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Soy sauce' FROM dish d WHERE d.name = 'Beef Stir-Fry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ginger' FROM dish d WHERE d.name = 'Beef Stir-Fry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Beef Stir-Fry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Broccoli' FROM dish d WHERE d.name = 'Beef Stir-Fry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Bell peppers' FROM dish d WHERE d.name = 'Beef Stir-Fry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Carrots' FROM dish d WHERE d.name = 'Beef Stir-Fry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Onions' FROM dish d WHERE d.name = 'Beef Stir-Fry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Vegetable oil' FROM dish d WHERE d.name = 'Beef Stir-Fry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Chicken breast' FROM dish d WHERE d.name = 'Chicken Parmesan';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Breadcrumbs' FROM dish d WHERE d.name = 'Chicken Parmesan';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Parmesan cheese' FROM dish d WHERE d.name = 'Chicken Parmesan';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Marinara sauce' FROM dish d WHERE d.name = 'Chicken Parmesan';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Mozzarella cheese' FROM dish d WHERE d.name = 'Chicken Parmesan';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Spaghetti' FROM dish d WHERE d.name = 'Chicken Parmesan';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Olive oil' FROM dish d WHERE d.name = 'Chicken Parmesan';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Chicken Parmesan';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Chicken Parmesan';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Tortillas' FROM dish d WHERE d.name = 'Tacos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ground beef' FROM dish d WHERE d.name = 'Tacos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lettuce' FROM dish d WHERE d.name = 'Tacos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Tomatoes' FROM dish d WHERE d.name = 'Tacos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cheese' FROM dish d WHERE d.name = 'Tacos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salsa' FROM dish d WHERE d.name = 'Tacos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sour cream' FROM dish d WHERE d.name = 'Tacos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Guacamole' FROM dish d WHERE d.name = 'Tacos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Mixed vegetables' FROM dish d WHERE d.name = 'Vegetable Curry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Curry paste' FROM dish d WHERE d.name = 'Vegetable Curry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Coconut milk' FROM dish d WHERE d.name = 'Vegetable Curry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Onion' FROM dish d WHERE d.name = 'Vegetable Curry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Vegetable Curry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ginger' FROM dish d WHERE d.name = 'Vegetable Curry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Vegetable oil' FROM dish d WHERE d.name = 'Vegetable Curry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Vegetable Curry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Vegetable Curry';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pork ribs' FROM dish d WHERE d.name = 'BBQ Ribs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Bbq sauce' FROM dish d WHERE d.name = 'BBQ Ribs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Brown sugar' FROM dish d WHERE d.name = 'BBQ Ribs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Paprika' FROM dish d WHERE d.name = 'BBQ Ribs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic powder' FROM dish d WHERE d.name = 'BBQ Ribs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Onion powder' FROM dish d WHERE d.name = 'BBQ Ribs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'BBQ Ribs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'BBQ Ribs';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pizza dough' FROM dish d WHERE d.name = 'Margherita Pizza';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Tomato sauce' FROM dish d WHERE d.name = 'Margherita Pizza';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Mozzarella cheese' FROM dish d WHERE d.name = 'Margherita Pizza';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Fresh basil' FROM dish d WHERE d.name = 'Margherita Pizza';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Olive oil' FROM dish d WHERE d.name = 'Margherita Pizza';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Margherita Pizza';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Margherita Pizza';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Flour tortillas' FROM dish d WHERE d.name = 'Beef Burritos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ground beef' FROM dish d WHERE d.name = 'Beef Burritos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Rice' FROM dish d WHERE d.name = 'Beef Burritos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Beans' FROM dish d WHERE d.name = 'Beef Burritos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cheese' FROM dish d WHERE d.name = 'Beef Burritos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salsa' FROM dish d WHERE d.name = 'Beef Burritos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sour cream' FROM dish d WHERE d.name = 'Beef Burritos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lettuce' FROM dish d WHERE d.name = 'Beef Burritos';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Chicken breast' FROM dish d WHERE d.name = 'Chicken Fajitas';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Bell peppers' FROM dish d WHERE d.name = 'Chicken Fajitas';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Onions' FROM dish d WHERE d.name = 'Chicken Fajitas';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Fajita seasoning' FROM dish d WHERE d.name = 'Chicken Fajitas';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Tortillas' FROM dish d WHERE d.name = 'Chicken Fajitas';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Guacamole' FROM dish d WHERE d.name = 'Chicken Fajitas';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sour cream' FROM dish d WHERE d.name = 'Chicken Fajitas';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salsa' FROM dish d WHERE d.name = 'Chicken Fajitas';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Potatoes' FROM dish d WHERE d.name = 'Garlic Mashed Potatoes';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Garlic Mashed Potatoes';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Butter' FROM dish d WHERE d.name = 'Garlic Mashed Potatoes';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Milk' FROM dish d WHERE d.name = 'Garlic Mashed Potatoes';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Garlic Mashed Potatoes';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Garlic Mashed Potatoes';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Assorted vegetables' FROM dish d WHERE d.name = 'Grilled Vegetables';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Olive oil' FROM dish d WHERE d.name = 'Grilled Vegetables';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Balsamic vinegar' FROM dish d WHERE d.name = 'Grilled Vegetables';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Grilled Vegetables';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Grilled Vegetables';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cabbage' FROM dish d WHERE d.name = 'Coleslaw';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Carrots' FROM dish d WHERE d.name = 'Coleslaw';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Mayonnaise' FROM dish d WHERE d.name = 'Coleslaw';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Vinegar' FROM dish d WHERE d.name = 'Coleslaw';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Coleslaw';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Coleslaw';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Coleslaw';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Rice' FROM dish d WHERE d.name = 'Rice Pilaf';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Onion' FROM dish d WHERE d.name = 'Rice Pilaf';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Rice Pilaf';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Chicken or vegetable broth' FROM dish d WHERE d.name = 'Rice Pilaf';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Butter' FROM dish d WHERE d.name = 'Rice Pilaf';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Rice Pilaf';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Rice Pilaf';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Canned baked beans' FROM dish d WHERE d.name = 'Baked Beans';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Bacon' FROM dish d WHERE d.name = 'Baked Beans';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Onion' FROM dish d WHERE d.name = 'Baked Beans';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Brown sugar' FROM dish d WHERE d.name = 'Baked Beans';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Molasses' FROM dish d WHERE d.name = 'Baked Beans';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Mustard' FROM dish d WHERE d.name = 'Baked Beans';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Baked Beans';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Baked Beans';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cornmeal' FROM dish d WHERE d.name = 'Cornbread';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Flour' FROM dish d WHERE d.name = 'Cornbread';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Cornbread';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Baking powder' FROM dish d WHERE d.name = 'Cornbread';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Milk' FROM dish d WHERE d.name = 'Cornbread';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Eggs' FROM dish d WHERE d.name = 'Cornbread';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Butter' FROM dish d WHERE d.name = 'Cornbread';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Cornbread';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Romaine lettuce' FROM dish d WHERE d.name = 'Caesar Salad';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Croutons' FROM dish d WHERE d.name = 'Caesar Salad';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Parmesan cheese' FROM dish d WHERE d.name = 'Caesar Salad';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Caesar dressing' FROM dish d WHERE d.name = 'Caesar Salad';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Brussels sprouts' FROM dish d WHERE d.name = 'Roasted Brussels Sprouts';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Olive oil' FROM dish d WHERE d.name = 'Roasted Brussels Sprouts';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Roasted Brussels Sprouts';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Roasted Brussels Sprouts';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Roasted Brussels Sprouts';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Spinach' FROM dish d WHERE d.name = 'Creamed Spinach';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cream cheese' FROM dish d WHERE d.name = 'Creamed Spinach';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Heavy cream' FROM dish d WHERE d.name = 'Creamed Spinach';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Creamed Spinach';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Nutmeg' FROM dish d WHERE d.name = 'Creamed Spinach';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Creamed Spinach';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Creamed Spinach';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Potatoes' FROM dish d WHERE d.name = 'Roasted Potatoes';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Olive oil' FROM dish d WHERE d.name = 'Roasted Potatoes';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Garlic' FROM dish d WHERE d.name = 'Roasted Potatoes';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Rosemary' FROM dish d WHERE d.name = 'Roasted Potatoes';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Roasted Potatoes';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pepper' FROM dish d WHERE d.name = 'Roasted Potatoes';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Flour' FROM dish d WHERE d.name = 'Chocolate Chip Cookies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Butter' FROM dish d WHERE d.name = 'Chocolate Chip Cookies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Chocolate Chip Cookies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Brown sugar' FROM dish d WHERE d.name = 'Chocolate Chip Cookies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Eggs' FROM dish d WHERE d.name = 'Chocolate Chip Cookies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Vanilla extract' FROM dish d WHERE d.name = 'Chocolate Chip Cookies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Chocolate chips' FROM dish d WHERE d.name = 'Chocolate Chip Cookies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Baking soda' FROM dish d WHERE d.name = 'Chocolate Chip Cookies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Chocolate Chip Cookies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pie crust' FROM dish d WHERE d.name = 'Apple Pie';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Apples' FROM dish d WHERE d.name = 'Apple Pie';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Apple Pie';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cinnamon' FROM dish d WHERE d.name = 'Apple Pie';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lemon juice' FROM dish d WHERE d.name = 'Apple Pie';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Butter' FROM dish d WHERE d.name = 'Apple Pie';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cream cheese' FROM dish d WHERE d.name = 'Cheesecake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Cheesecake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Eggs' FROM dish d WHERE d.name = 'Cheesecake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sour cream' FROM dish d WHERE d.name = 'Cheesecake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Vanilla extract' FROM dish d WHERE d.name = 'Cheesecake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Graham cracker crust' FROM dish d WHERE d.name = 'Cheesecake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Flour' FROM dish d WHERE d.name = 'Brownies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cocoa powder' FROM dish d WHERE d.name = 'Brownies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Brownies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Butter' FROM dish d WHERE d.name = 'Brownies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Eggs' FROM dish d WHERE d.name = 'Brownies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Vanilla extract' FROM dish d WHERE d.name = 'Brownies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Chocolate chips' FROM dish d WHERE d.name = 'Brownies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Brownies';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ladyfingers' FROM dish d WHERE d.name = 'Tiramisu';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Mascarpone cheese' FROM dish d WHERE d.name = 'Tiramisu';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Coffee' FROM dish d WHERE d.name = 'Tiramisu';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cocoa powder' FROM dish d WHERE d.name = 'Tiramisu';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Tiramisu';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Rum' FROM dish d WHERE d.name = 'Tiramisu';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Eggs' FROM dish d WHERE d.name = 'Tiramisu';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Assorted fruits' FROM dish d WHERE d.name = 'Fruit Salad';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Honey' FROM dish d WHERE d.name = 'Fruit Salad';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lemon juice' FROM dish d WHERE d.name = 'Fruit Salad';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Mint leaves' FROM dish d WHERE d.name = 'Fruit Salad';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Heavy cream' FROM dish d WHERE d.name = 'Creme Brulee';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Creme Brulee';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Vanilla extract' FROM dish d WHERE d.name = 'Creme Brulee';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Egg yolks' FROM dish d WHERE d.name = 'Creme Brulee';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Flour' FROM dish d WHERE d.name = 'Carrot Cake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Carrot Cake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Carrots' FROM dish d WHERE d.name = 'Carrot Cake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Eggs' FROM dish d WHERE d.name = 'Carrot Cake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Vegetable oil' FROM dish d WHERE d.name = 'Carrot Cake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Baking powder' FROM dish d WHERE d.name = 'Carrot Cake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cinnamon' FROM dish d WHERE d.name = 'Carrot Cake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cream cheese frosting' FROM dish d WHERE d.name = 'Carrot Cake';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Heavy cream' FROM dish d WHERE d.name = 'Panna Cotta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Panna Cotta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Gelatin' FROM dish d WHERE d.name = 'Panna Cotta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Vanilla extract' FROM dish d WHERE d.name = 'Panna Cotta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Fresh berries' FROM dish d WHERE d.name = 'Panna Cotta';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Flour' FROM dish d WHERE d.name = 'Lemon Bars';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Butter' FROM dish d WHERE d.name = 'Lemon Bars';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Lemon Bars';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Eggs' FROM dish d WHERE d.name = 'Lemon Bars';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lemon juice' FROM dish d WHERE d.name = 'Lemon Bars';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lemon zest' FROM dish d WHERE d.name = 'Lemon Bars';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Powdered sugar' FROM dish d WHERE d.name = 'Lemon Bars';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'White rum' FROM dish d WHERE d.name = 'Mojito';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lime juice' FROM dish d WHERE d.name = 'Mojito';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Mint leaves' FROM dish d WHERE d.name = 'Mojito';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Mojito';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Soda water' FROM dish d WHERE d.name = 'Mojito';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ice' FROM dish d WHERE d.name = 'Mojito';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Tequila' FROM dish d WHERE d.name = 'Margarita';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lime juice' FROM dish d WHERE d.name = 'Margarita';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Triple sec' FROM dish d WHERE d.name = 'Margarita';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Salt' FROM dish d WHERE d.name = 'Margarita';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ice' FROM dish d WHERE d.name = 'Margarita';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Strawberries' FROM dish d WHERE d.name = 'Strawberry Smoothie';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Yogurt' FROM dish d WHERE d.name = 'Strawberry Smoothie';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Milk' FROM dish d WHERE d.name = 'Strawberry Smoothie';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Honey' FROM dish d WHERE d.name = 'Strawberry Smoothie';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ice' FROM dish d WHERE d.name = 'Strawberry Smoothie';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Whiskey' FROM dish d WHERE d.name = 'Old Fashioned';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Old Fashioned';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Bitters' FROM dish d WHERE d.name = 'Old Fashioned';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Orange peel' FROM dish d WHERE d.name = 'Old Fashioned';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ice' FROM dish d WHERE d.name = 'Old Fashioned';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Pineapple juice' FROM dish d WHERE d.name = 'Piña Colada';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Coconut cream' FROM dish d WHERE d.name = 'Piña Colada';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'White rum' FROM dish d WHERE d.name = 'Piña Colada';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ice' FROM dish d WHERE d.name = 'Piña Colada';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Mango' FROM dish d WHERE d.name = 'Mango Lassi';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Yogurt' FROM dish d WHERE d.name = 'Mango Lassi';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Mango Lassi';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cardamom' FROM dish d WHERE d.name = 'Mango Lassi';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ice' FROM dish d WHERE d.name = 'Mango Lassi';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Milk' FROM dish d WHERE d.name = 'Hot Chocolate';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Cocoa powder' FROM dish d WHERE d.name = 'Hot Chocolate';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Hot Chocolate';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Vanilla extract' FROM dish d WHERE d.name = 'Hot Chocolate';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Whipped cream' FROM dish d WHERE d.name = 'Hot Chocolate';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Chocolate shavings' FROM dish d WHERE d.name = 'Hot Chocolate';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Tea bags' FROM dish d WHERE d.name = 'Iced Tea';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Water' FROM dish d WHERE d.name = 'Iced Tea';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Iced Tea';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lemon slices' FROM dish d WHERE d.name = 'Iced Tea';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ice' FROM dish d WHERE d.name = 'Iced Tea';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Vodka' FROM dish d WHERE d.name = 'Espresso Martini';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Espresso' FROM dish d WHERE d.name = 'Espresso Martini';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Coffee liqueur' FROM dish d WHERE d.name = 'Espresso Martini';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar syrup' FROM dish d WHERE d.name = 'Espresso Martini';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ice' FROM dish d WHERE d.name = 'Espresso Martini';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lemon juice' FROM dish d WHERE d.name = 'Sparkling Lemonade';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sparkling water' FROM dish d WHERE d.name = 'Sparkling Lemonade';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Sugar' FROM dish d WHERE d.name = 'Sparkling Lemonade';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Lemon slices' FROM dish d WHERE d.name = 'Sparkling Lemonade';
INSERT IGNORE INTO cooking (dish, ingredient) SELECT d.id, 'Ice' FROM dish d WHERE d.name = 'Sparkling Lemonade';
